- nodejs/dist/uws.js
µWS works only on node 4+ so I think it makes sense to use ES2015.
I did not test the changes so there might be bugs.
> Rewrite the ws interface in ES2015

- README.md
- src/uWS.cpp
> Implement duplicate socket on Windows.

- nodejs/dist/uws.js
Not doing so is a V8 performance anti-pattern.
See [Hidden Classes](http://www.html5rocks.com/en/tutorials/speed/v8/)
> Ensure all properties exist during construction time.

- nodejs/dist/uws.js
Add an optional callback to socket.send.
This is for ws compatibility.
> Add an optional callback to socket.send

- .gitignore
- benchmarks/Makefile
- benchmarks/README.md
> Use $(CXX) and add build instructions for benchmarks

- nodejs/dist/uws.js
This sets the `onConnection` listener only when the socket has been closed to prevent possible race conditions.
Closes #86.
> Fix possible race condition in handleUpgrade

- nodejs/Makefile
This is why you ended up with src/src
> Correct cp call, fix #99 again

- nodejs/dist/uws.js
Kind of speaks for itself. I wasn't sure what to use as default messages, so I'm curious what you think. Feel free to edit them as you like. 
Also, `socket.end()` is replaced by `socket.destroy()`. Not sure which of them should be used. `ws` uses destroy, although it should be used in case of failure (which this isn't). Any thoughts?
> Send client verification failure reasons to socket

- .gitignore
- examples/meson.build
- meson.build
- src/meson.build
```
mkdir build && cd build
meson ..
ninja
```
make sure to install [meson](https://github.com/mesonbuild/meson), python and ninja on your system.
> add meson build support

- meson.build
fixes strange utf8 localization issues on CI platforms
> update project name in meson.build

- meson.build
for zlib, openssl, libuv dependencies under meson build
> add minimum version requirements for dependencies

- src/WebSocket.cpp
- src/WebSocket.h
there aren't any tests but the build is sucessfull.
> fix params of send, ping & formatMessage calls

- nodejs/dist/uws.js
> Fix nodejs - server.close()

- README.md
Update the C++ example in the README.md so that it will compile.
> Update C++ example in README.md

- nodejs/dist/uws.js
> Fix ws.ping

- src/WebSocketProtocol.h
> Properly handle error codes in the Private Use range (4000-4999)

- src/Networking.h
Closes #351 
This has been a problem for windows users. The solution was found some time ago in the issue, but was never fixed. 
Let me know if there's anything that needs to be changed.
Thanks 😄
> Fix unresolved external symbol with NodeData::asyncCallback

- src/HTTPSocket.h
Nice to have for responding to CORS pre-flight requests.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
> Add HTTP verb OPTIONS

- src/HTTPSocket.h
#419 had a stupid typo, my bad :(
you are too fast
> Fix silly typo

- src/Group.cpp
- src/Group.h
- src/Hub.h
- src/WebSocket.h
I was in need of a fix for #385 myself, and implemented this PR as simple solution
> add callback for transferred sockets

- src/Node.h
> Fix memory leak when getting INVALID_SOCKET

- src/Hub.cpp
- tests/main.cpp
fix a bug about multiple errors emitted for one connection which make resource management of userDate difficult.
> fix a bug about multiple errors emitted for one connection 

- src/Asio.h
- src/Epoll.h
- src/HTTPSocket.cpp
- src/Hub.cpp
- src/Libuv.h
- src/Node.h
- src/Socket.h
Fixes name collision when compiling with libuv headers
> UV_READABLE and UV_WRITABLE -> UWS_READABLE, UWS_WRITABLE

- src/Backend.h
follow-up of https://github.com/uNetworking/uWebSockets/pull/759
> define USE_EPOLL only if not defined already

- src/HttpParser.h
Fix https://github.com/uNetworking/uWebSockets.js/issues/117 bug
> Remove "?" in getQuery response

- src/Loop.h
> Fix multithreaded loop clean-up, fixes #888

- src/WebSocketExtensions.h
> Fix compile error: 'INT_MIN' was not declared in this scope

- examples/HttpServer.cpp
- examples/helpers/AsyncFileReader.h
- examples/helpers/AsyncFileStreamer.h
Tested serving an index.html file from a public root: Used ssl and curl
```
curl --request GET --insecure --key ../privkey.pem --cert ../fullchain.pem --include \
--no-buffer \
--header "Connection: Upgrade" \
--header "Upgrade: websocket" \
--header "Host: roger-G74Sx:3000" \
--header "Origin: https://roger-G74Sx:3000" \
https://roger-G74Sx:3000/
```
successfully
> a few upgrades for the HttpServer example

- Makefile
> opti: makefile add clean

- README.md
- misc/READMORE.md
- misc/main.cpp
https://github.com/uNetworking/uWebSockets.js/issues/377
> Minor example updates

- examples/BroadcastingEchoServer.cpp
- examples/EchoServer.cpp
- examples/EchoServerThreaded.cpp
Fixes #1130 and follows up on #1116
> Fix TAD on old examples by adding .upgrade handler

- src/WebSocket.h
This will be merged after fuzzing finds the bug
> Fix WebSocket::close being called in close handler

- src/WebSocket.h
fix https://github.com/uNetworking/uWebSockets.js/issues/653
> prevent unsub error

- src/App.h
To be merged when we are 100% sure, that Safari 15.4 is fixed.
> Updated Safari hack to target 15.0-15.3 (#1347)

- capi/libuwebsockets.cpp
- capi/libuwebsockets.h
added getCaseSensitiveMethod featured in v20.28.0 [Latest](https://github.com/uNetworking/uWebSockets/releases/latest)
> added uws_req_get_case_sensitive_method in C API

- capi/libuwebsockets.cpp
1. add uws_res_close
2. fix uws_res_upgrade
3. fix uws_res_override_write_offset
4. add subscription events
Solves https://github.com/uNetworking/uWebSockets/issues/1566 and https://github.com/uNetworking/uWebSockets/issues/1542
> fix(CAPI) uws_res_upgrade, uws_res_override_write_offset, feat(CAPI) uws_res_close and subscription events

- src/HttpParser.h
Related to: https://github.com/uNetworking/uWebSockets.js/issues/879
> Fix chunked body handling in fallback routine

- examples/helpers/AsyncFileStreamer.h
Hi,
I think there's a bug in the AsyncFileStreamer helper. 
Files larger than what can be written in first chunk cause a crash when downloading 2nd time with Chrome
proposed change fixes it for me
Erik
> Prevent reading beyond end of file

- src/AsyncSocket.h
try fix https://github.com/uNetworking/uWebSockets/issues/1617
> #1617 fix warning: 'sprintf' is deprecated from macOS

- src/PerMessageDeflate.h
Fixes https://github.com/uNetworking/uWebSockets/issues/1650
> Restore the bytes overwritten by the tail after inflation

- capi/libuwebsockets.cpp
- capi/libuwebsockets.h
Hello! 
This PR adds `uws_app_close` function to the C API, which is call native app `close` method.
Please, consider to merge.
> Add uws_app_close function to CAPI

- src/HttpParser.h
> AsyncFileStreamer typo

- misc/READMORE.md
> Update user manual

- src/AsyncSocketData.h
add buffer.shrink_to_fit() to reduce memory when clear buffer.
> add buffer.shrink_to_fit() to reduce memory
