uNetworking/uWebSockets

nodejs/dist/uws.js
Right now the error listener is invoked with a string.
It is usually expected to receive an error instance in the error listener.
=> Pass an error instance to the error listener

src/uWS.cpp
Socket identifier is `p` not `socket`.
=> Fix typo (socket → p)

nodejs/dist/binding.gyp
This file won't work "as is":
- source files must be copied in dist dir
- uws.js does not load `uws.node` but `uws_xx_yy.node`
but the bulk is there.
=> Preliminary work on binding.gyp

nodejs/dist/binding.gyp
Fix for https://github.com/alexhultman/uWebSockets/issues/93
=> Move -stdlib=libc++ to linker flag

nodejs/dist/binding.gyp
This should fix compilation errors when building on OS X via node-gyp.
Closes #93.
=> Fix build error on OS X

nodejs/dist/uws.js
A library, module, addon, whatever, has no rights to exit process unilateraly.
=> rethrow an error instead of exiting process

src/uWS.cpp, src/uWS.h
This fixes some warnings when building with node-gyp on OS X:
```
> node-gyp rebuild
CXX(target) Release/obj.target/uws/src/uWS.o
../src/uWS.cpp:163:54: warning: field 'port' will be initialized after field 'master' [-Wreorder]
Server::Server(int port, bool master, string path) : port(port), master(master), path(path)
^
../src/uWS.cpp:633:31: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
for (int i = 0; i < h.value.second; i++) {
~ ^ ~~~~~~~~~~~~~~
2 warnings generated.
CXX(target) Release/obj.target/uws/src/addon.o
SOLINK_MODULE(target) Release/uws.node
ACTION binding_gyp_action_after_build_target_move_lib uws
TOUCH Release/obj.target/action_after_build.stamp
```
=> Fix compiler warnings

README.md
this is the error(node 6.2.0):
TypeError: Class constructor Server cannot be invoked without 'new'
at RPCserver (/home/capaj/git_projects/zahrajeme.cz-backend/node_modules/socket.io-rpc/main.js:22:37)
at Object.<anonymous> (/home/capaj/git_projects/zahrajeme.cz-backend/server.js:8:22)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Function.Module.runMain (module.js:575:10)
at startup (node.js:160:18)
at node.js:449:3
=> fixes an error when sample code is run

nodejs/dist/package.json
This should stop npm from installing a broken module on Windows. The `os` could also be changed to `"os" : [ "!win32" ]` if Solaris and BSD are known to work.
=> specify os compatibilty in package.json

main.cpp, nodejs/addon.cpp, nodejs/dist/uws.js, src/Server.cpp, src/Server.h, src/WebSocket.cpp
In our case (and I'm sure a lot of other cases as well) it would be more logical to have clients ping the server and handle those accordingly. To support this, I added an onPing event listener. When a `ping` is received, a `pong` is still sent back, but a callback is also triggered.
=> onPing listener

CMakeLists.txt, examples/CMakeLists.txt
find_package is used to look for openssl and zlib.
find_path/find_library are used to look for libuv, as CMake do not have built-in support for libuv lookup.
This change make cmake finding all decencies automatically and report any missing library at configure time instead of compiling or linking time.
CMAKE_CXX_STANDARD is also set to force use C++11. target_compile_features with cxx_nullptr statements are removed.
=> Add CMake dependency lookup, force use C++11 standard.

src/Server.cpp
This pull request sets SO_REUSEADDR on the listening socket. 
Reason:
When killing servers with connections still connected, active sockets will enter TIME_WAIT state. If you try to start the server again, `ERR_LISTEN` will be thrown. This forbids us to restart server with live traffic.
=> Set SO_REUSEADDR before bind.

nodejs/dist/uws.js
Our clients weren't trying to reconnect when the verification failed, this seems to be the reason why...
=> Fix typo in node.js client verification

examples/meson.build, meson.build, src/meson.build
This commit simplifies importing uWS to other meson projects.
Now only a single line will handle imports(both system, fallback to git repo) -
```uWS_dep = dependency('uWS', fallback : ['uWS', 'uWS_dep'])```
=> add dependency declaration to meson.build

nodejs/dist/uws.js
This provides the user with a lead to the actual cause instead of wrongfully blaming the build environment 😉.
=> provide a more helpful error on Windows when loading fails

nodejs/addon.h, nodejs/dist/uws.js, src/Hub.cpp, src/Hub.h
This PR allows the `Sec-Websocket-Protocol` header to be passed from Node to C++ so that the header can be echoed back in the response. This prevents the following error: `Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received`, similar to https://github.com/uWebSockets/uWebSockets/issues/263
Please let me know if there's anything you'd like done differently, as I am very new to this repo. Thanks!
=> Pass the Sec-Websocket-Protocol header through from Node

nodejs/dist/binding.gyp
As described in #349.
Apologies if it's not the right way to do it, initially I tried to use `copies` but that didn't seem to have the option to change a name.
=> Fix for node-gyp rebuild on Windows (cmd/powershell)

src/Group.h, src/HTTPSocket.cpp, src/HTTPSocket.h, src/Hub.cpp
This exposes the HTTPParser to onConnection's upgradeinfo. I have also implemented a simpler way to parse the headers, through `uWS::UpgradeInfo::getRequestHeaders()`, which returns a `std::map<std::string, std::string>`. There's a small overhead of copying/allocating the strings and the map, but people can still use the HTTPParser if zero-copy parsing is required.
**Example:**
```cpp
int main()
{
uWS::Hub h;
h.onConnection([](uWS::WebSocket<uWS::SERVER> ws, uWS::UpgradeInfo ui) {
// headers
const std::map<std::string, std::string>& headers = ui.getRequestHeaders();
for (auto i = headers.begin(); i != headers.end(); i++) {
// i->first: header key; i->second: header value
std::cout << i->first << ": " << i->second << std::endl;
}
});
h.onMessage([](uWS::WebSocket<uWS::SERVER> ws, char …
```
=> allow access to httpheaders on connection handler

CMakeLists.txt
Use `set_property` instead of `set` for `CMAKE_CXX_STANDARD` or
`CXX_STANDARD`. Only tested with GNU compilers.
The compiler check can probably be omitted if the flag was changed to `--std=c++11`.
=> Fix CMakeLists.txt to specify C++ 11 standard

nodejs/dist/uws.js
instead of creating an error object we can just simulate it, since we won't have a trace anyway
=> update uws error

nodejs/dist/uws.js
This allows to be listener free in the callback, which is a reasonable
assumption when calling a once() statement.
=> Convert callback calls of WebSocket once() to Tail calls

src/HTTPSocket.cpp, src/HTTPSocket.h, src/Hub.cpp, src/Hub.h
To simplify testing of ui.subprotocol, using just the uWebSockets library, teach the `uWS::WebSocket<uWS::CLIENT>` how to set an optional Sec-WebSocket-Protocol header.
To attempt to minimise API change this is done by adding an extra optional parameter to the end of the Hub::connect() function.
=> Teach client connection about "Sec-WebSocket-Protocol" header.

nodejs/dist/uws.js
ported from: https://github.com/primus/primus/pull/531
fixes: https://github.com/uWebSockets/uWebSockets/issues/326
Not sure if the checks for `.writeable` and `.readable` like it was done for primus are necessary, so I went with a boolean check on the handle.
Can't run autobahn right now because of https://github.com/uWebSockets/uWebSockets/issues/430.
=> nodejs: don't attempt to upgrade closed sockets

src/Group.cpp, src/Networking.h, src/Node.h
This works for me. Take a look and let me know what you think. I had to copy some of the code from Socket.close() into the Group.cpp stopListening() call because there is no uv_poll_t Socket while the timer is running. There might be a way to do this a bit cleaner without the code replication.
=> Accept issue

src/Hub.cpp, src/Hub.h, src/Node.h
It should be possible to explicitly specify the address to bind to instead of just listening on all interfaces.
This change adds a "host" argument to `Hub::listen` which gets passed to `getaddrinfo()` in `Node.h` while preserving API compatibility.
=> Allow listening on specific addresses

README.md
Add in explicit instructions for users so they don't accidentally mix up x86 libraries with the x64-by-default build of uWebsockets.
=> Update instructions for Vcpkg/Windows

nodejs/src/uws.js
Both nodejs' http and ws libs support random server listening port setting.
In example, someone might like to do:
```js
var WebSocketServer = require('uws').Server;
var wss = new WebSocketServer({ port: 0 })
```
Without this patch, the server would just return silently, since the ```options.port``` check would fail erroneously.
Also, sane checks for server object creation are added here.
Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>
=> nodejs: support random server port definition

src/HTTPSocket.cpp, src/Networking.h, src/WebSocket.cpp
I'm using the libuv backend, and get an assertion fail from libuv. I'm testing my server for handling aborted transfers. To test this, I telnet onto the web-server, request a file and exit the telnet session. The server has a breakpoint set early during processing of the HTTP request, and resumes execution after I've closed the telnet session.
The server will call `changePoll(this);` in Socket.h on line 343, which later causes libuv to fail with the following assertion:
libuv/src/unix/poll.c:105: uv_poll_start: Assertion `!uv__is_closing(handle)' failed.
=> clear pollQueue onEnd

src/Node.h, src/Socket.h
This pull request contain following modifications:
* Handling ::connect error
* Checking return value from recv function properly
There are some issues reported by static analysis tool. But I am not sure that they should be fixed or not.
1. Error from setsockopt is not handled.
2. NodeData and Socket have derived classes, but they don't contain a virtual destructor.
=> Check error properly

README.md, examples/echo.cpp
In order to keep the examples minimal, just return an exit error code.
=> Add basic port validation

Makefile, src/Networking.h
This fixes the build of this library on SunOS based platforms like SmartOS or illumos.
=> Support SunOS based platforms

Makefile
If we don't install the library globally, we get the following error
from the linker on Linux:
$ make tests
g++ -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -I/usr/local/include -std=c++11 -O3 -g tests/main.cpp -Isrc -o testsBin -lpthread -luWS -lssl -lcrypto -lz -L/usr/local/lib -luv
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -luWS
collect2: error: ld returned 1 exit status
=> Test local libuWS library if available

src/Hub.h
Easy way to make a onTransfer from hub.
If not you need to make something like this:
```
m_Hub->getDefaultGroup<uWS::CLIENT>().onTransfer([this]( uWS::WebSocket<uWS::CLIENT> *ws ) {
std::cout << "WebSocket: Client Transfer" << std::endl;
m_ws = ws;
});
```
instance of:
```
m_Hub->onTransfer([this](uWS::WebSocket<uWS::CLIENT> *ws) {
std::cout << "WebSocket: Client Transfer" << std::endl;
m_ws = ws;
});
```
=> Add onTransfer for clients on Hub class

Makefile
This change is being proposed in order to include µWS in the Homebrew package manager. Specifically, it's been requested that the Makefile be able to accept commands such as
```
make install PREFIX=/usr/local/Cellar/microws/0.14.4
```
Installation prefix still defaults to `/usr` on Linux and `/usr/local` on Darwin if no prefix is set.
=> Allow for installation to custom prefix

src/Node.h
small fix to make clear `bind` is called from a global namespace.
this fixes the issue if you use `using namespace std;` in your program.
=> make clear to call bind() from global namespace

tests/main.cpp
Hi,
For Debian/Ubuntu, ``dash`` is used as ``/bin/sh`` (https://wiki.ubuntu.com/DashAsBinSh) and `dash` does not support ``&>`` style redirection(https://wiki.ubuntu.com/DashAsBinSh#A.26.3E). I tried to change the ``SHELL`` environmental variable to use ``/bin/bash``, but ``popen`` does not seem to use that variable.
This PR changes the redirection style.
I tested by the following Dockerfile
```
FROM ubuntu:16.04
#FROM debian:jessie
RUN apt-get update && \
apt-get install -y build-essential libssl-dev netcat-openbsd
ADD . /uWebSockets
RUN cd uWebSockets && make && make install && g++ -std=c++11 -O3 tests/main.cpp -Isrc -o testsBin -lpthread -L. -luWS -lssl -lcrypto -lz
ENV SHELL /bin/bash
CMD cd uWebSockets && ./testsBin
```
```bash
$ docker build -t test .
$ docker run --rm --net=host …
```
=> Use '> /dev/null 2>&1' redirection

src/Epoll.h
In Epoll version of Async::close(), delete itself as Async* instead of Poll*
=> Small fix for Epoll version of Async

src/Hub.cpp
From the RFC 2616, Section 14.23 ([check it](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23)):
> The Host request-header field specifies the Internet host and port number of the resource being requested, as obtained from the original URI...
and 
> A "host" without any trailing port information implies the default port for the service requested
It seems that you are not specifying the port in the Host Header when creating your upgrade HTTP request, which is causing the connection to drop on some servers.
=> Add port info in HTTP Host header

src/Extensions.h, src/Group.h, src/HTTPSocket.h, src/Hub.h, src/Networking.h, src/Node.h, src/WebSocketProtocol.h
Hi,
I want to use uWebSockets as a websocket client from behind a proxy.
To implement this, I overrided [``connect``](https://github.com/otamachan/uWS_proxy/blob/2454ff8cc30bbfe77dab90dc580f36a269524944/src/ProxyHub.cpp#L102) method of ``Hub`` class and made a [``ProxyHttpSocket``](https://github.com/otamachan/uWS_proxy/blob/8f9e1a5e15737839b7b86eeaa391b2aa9d8f784e/src/ProxyHTTPSocket.h) class derived from ``HttpSocket`` class to communicate with a proxy server to establish a connection. Unfortunately  some of the members are not accessible in a derived class. This PR makes them accessible.
A full sample is [here](https://github.com/otamachan/uWS_proxy).
If you know a better way to use uWebSockets behind a proxy, please let me know.
Thanks in advance.
=> Make members accessible in derived class

src/Asio.h, src/Epoll.cpp, src/Epoll.h, src/Hub.h, src/Libuv.h, src/Node.cpp, src/Node.h
For use in applications that already have a primary event loop, so they cannot call blocking run(). They may instead call poll() within this loop to delegate to uWebSocket's secondary event loop (whether Asio, libuv or epoll). It is assumed that this will be called very frequently, e.g. "busy spin".
=> Support external event loops via non-blocking poll() alt. to run()

src/Asio.h
`native_type` has been deprecated since 1.47.0 and removed in 1.66.0, so uWebSockets no longer builds against the latest versions of boost.  `native_handle_type` is the replacement for `native_type` and has existed since 1.47.0.
This PR updates Asio.h to use `native_handle_type` in place of `native_type`.
=> Update boost::asio:: ... ::native_type to  boost::asio:: ... ::native_handle_type

src/Networking.cpp
It was possible for it to not have been initialized yet if we're calling createContext in the initialization of a global variable in another file, since there's nothing that guarantees the initialization order between global variables in different files.
There's also another init further down in this file related to Windows, but I haven't been using uWebSockets on Windows that much to hit an issue with that yet.
=> Fix SSL library init order

src/Epoll.cpp, src/Epoll.h
Fixed two major bugs with Epoll timers.
1) Rewrote the timer check in Loop::run to reset the next epoll_wait() epollTimeout/delay if there was socket activity but no executed timer. This fixes timer resolution to be very accurate, regardless of i/o activity.
2) Critical bug fix where if while executing a timer callback, the callback stop()'d a different timer, the loop code would "continue" thinking the current timer was stopped. This was because it uses a Loop:: boolean that is global to that context. Added checking to make sure the current processing timer was stopped. The result of this bug would be that the timer would execute a second time immediately.
One other note is that if during the timer check loop your callback triggers the creation of a new Timer that wants to execute …
=> Epoll Bug Fixes - Timer Resolution Accuracy Improved

src/App.h
Depends on https://github.com/uNetworking/uSockets/pull/48
Per the discussions on https://github.com/uNetworking/uWebSockets.js/issues/118 from @davidmurdoch, this PR adds `listen()` functions to accept `options`.
Feel free to edit the code directly as you see fit @alexhultman
=> Add Functions to Accept Listening Options

src/HttpParser.h
I tried to use getHeader method on HttpRequest and found out that it did not perform case insensitive search on headers.
It is specified by [RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1"](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) that headers should be case insensitive:
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.
=> Clarify getHeader argument meaning

examples/BroadcastingEchoServer.cpp, examples/EchoServer.cpp, examples/EchoServerThreaded.cpp
This PR fixes problems building examples apps (gcc-8.3).
```
error: no matching function for call to 'uWS::TemplatedApp<false>::ws<main()::PerSocketData>(const char [3], <brace-enclosed initializer list>)'
}).listen(9001, [](auto *token) {
^
```
=> Fix example build error

src/TopicTreeDraft.h
If we want to utilizate  uint64 type of ```intersection``` variable. We should convert 1 to 64 bit value.
Otherwise, if value of ```i``` exceeds 32 we can get an unobvious value.
=> Type casting fix

src/HttpResponse.h
This could be done by defining UWS_HTTPRESPONSE_NO_WRITEMARK macro.
=> Optionally prevent sending of "uWebSockets" header

src/App.h
Remove unused capture `httpContext` in `onHttp` lambda.
=> Remove unused capture `httpContext` in `onHttp` lambda.

src/QueryParser.h
in the original version, access outside the array is possible. it seems to me that the code looks more secure.
=> fix access outside the array

benchmarks/Makefile
Hi Alex,
Benchmarks didn't compile because a cpp file sni_tree.cpp was added, and the previous makefile only included .c files, leading to missing symbols at the linking stage. As LTO generated object files are incompatible between GCC and LLVM, it is useful to regenerate all object files in uSockets. This pull request does so. 
As on Linux GCC is the default, but the fuzzing requires libfuzzer from LLVM, using LLVM is actually the only way to reach the benchmarks target in the root Makefile, I found that using `WITH_OPENSSL=1 CC=clang CXX=clang++ make` is the only way to compile all targets, as GCC doesn't support fuzzing. Nontheless, if people have compiled using plain make and thus using the default GCC on Linux, the makefile in the benchmarks directory still works as it regenerated …
=> Makes benchmarks compile with clang

src/WebSocketContext.h
in WebSocketContext::us_socket_context_on_writable()
=> Fix checking if we actively drain backpressure

src/HttpResponse.h, src/HttpResponseData.h
Commits f2198ccfac140798ee066c5a3c5235b396473205 and 4fcfe49bcce574c0aca7ab6409f81a725bf8f88c
are fixed 2Gb limit, but introduced 4Gb limit on Rasperry Pi 32 bit.
This is because the max value of type `size_t` is `4294967295` on this
system.
Furthermore, the Standard Library use `std::uintmax_t` as a type
of value returned by `std::filesystem::file_size`.
=> Fix 4Gb limit streamed HTTP on Raspberry Pi 32bit

src/TopicTree.h
fix #1269
updated file: [TopicTree.h](https://github.com/uNetworking/uWebSockets/blob/6340368194881f6ab164b15619349e8856a70eca/src/TopicTree.h#L90-L133)
```c++
if (!senderForMessages.empty()) {
std::pair<size_t, size_t> toEmit = {};
unsigned int startAt = 0;
/* Iterate each message looking for any to skip */
for (auto &message : holes) {
/* If this message was sent by this subscriber skip it */
bool skipMessage = false;
for (unsigned int i = startAt; i < senderForMessages.size(); i++) {
if (senderForMessages[i] > message.messageId) {
startAt = i;
break;
}
if (message.messageId == senderForMessages[i]) {
skipMessage = true;
startAt = ++i;
break;
}
}
/* Collect messages until a skip, then emit messages */
if (!skipMessage) {
toEmit.first += message.lengths.first;
toEmit.second += …
```
=> ws.publish() - fix #1269

src/AsyncSocket.h, src/HttpResponse.h, src/PerMessageDeflate.h, src/WebSocketContextData.h, src/WebSocketProtocol.h
* uSockets/src/internal/networking/bsd.h
\#include "libusockets.h" for LIBUS_SOCKET_DESCRIPTOR
* uWebSockets/src/AsyncSocket.h
\#include \<cstring\> for memcpy
\#include "libusockets.h" for us_socket
* uWebSockets/src/HttpResponse.h
\#include "HttpContext.h" for HttpContext
* uWebSockets/src/PerMessageDeflate.h
\#include \<cstdint\> for uint32_t
* uWebSockets/src/WebSocketContextData.h
\#include "Loop.h" for Loop::get()
\#include "AsyncSocket.h" for AsyncSocket
* uWebSockets/src/WebSocketProtocol.h
\#include \<libusockets.h\> for WIN32_EXPORT macro
=> Fixes #1306 - transitive dependencies in header files

src/WebSocket.h, src/WebSocketContext.h, src/WebSocketContextData.h
Just using the ping-timeout as end-timeout for now.
Setting the timeout after sending the close-message should also overwrite the timeout set by `send` if `resetIdleTimeoutOnSend` is active.
Also check `webSocketData->isShuttingDown` in `on_timeout()` ... this seems to be a small bug in any case (a ping may have been sent on a socket on timeout after being `shutdown()`).
=> Shorter socket-timeouts after WebSocket::end() (#1245)

src/WebSocketProtocol.h
Hi,
it seems like WebSocket-masking is not done for continuations (see diff below).
In fact, I observed for our project that - if a websocket frame is split into several TCP frames - only the first one is demasked. The provided patch should fix that
=> Fixed masking for continuations

src/App.h
The main goal is to be able to pass custom ciphers from node.js (In App options) and have them used internally in uSockets
Followup of https://github.com/uNetworking/uSockets/pull/171
=> Allow passing custom ciphers via options

src/WebSocketContextData.h
`TopicTreeMessage` and `TopicTreeBigMessage` are defined in App.h. This means that if App.h doesn't come first somehow, then there will be an error as those definitions can't be found. So declare it here, just like it was done with `WebSocket` and let the actual definition come later.
I was able to get this behavior by only including HttpParser.h and HttpResponse.h, as I was building a helper library for my use case.
=> Declare TopicTreeMessage and TopicTreeBigMessage prior to use

src/HttpParser.h
The HelloWorld example failed on Windows (with MSVC) whereas it succeeded to run on macOS (XCode). So debugging both platforms in parallel revealed the parsing error due to using '0UL' instead of '0ULL'. 
I checked both platforms with '0ULL' successfully now though I did not check Linux.
=> Use ULL (unsigned long long) instead of UL

src/App.h, src/TopicTree.h, src/WebSocketContextData.h
`TopicTreeMessage` and `TopicTreeBigMessage` definitions are required prior to including App.h since I previously (#1507) changed it to do a forward declaration. The forward declaration created issues as other parts ended up accessing the structs, which require the definitions.
=> Move TopicTreeMessage and TopicTreeBigMessage to TopicTree.h

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where uWebSockets already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
=> Add GitHub Action CIFuzz integration

capi/libuwebsockets.cpp, capi/libuwebsockets.h, src/HttpResponse.h
Fixes https://github.com/uNetworking/uWebSockets/issues/1567 and fixes a typo in a comment that I noticed.
=> Fix some typos

src/LoopData.h
This PR fixes the following compiler warning:
```cpp
../subprojects/uwebsockets/include/uwebsockets/LoopData.h:79:62: error: ‘ GMT’ directive output may be truncated writing 4 bytes into a region of size between 2 and 16 [-Werror=format-truncation=]
79 |         snprintf(date, 32, "%.3s, %.2d %.3s %d %.2d:%.2d:%.2d GMT",
|                                                              ^~~~
```
The warning is because each occurrence of `%.2d` could potentially add a minus sign. Changing to `%.2u` makes this impossible and the warning disappears.
I use **GCC 10.3.0** on **Ubuntu 20.04**, the relevant compiler flags are:
```sh
-Wall -Winvalid-pch -Wextra -Werror -std=gnu++20
```
=> Fix [-Werror=format-truncation] compiler warning

capi/libuwebsockets.cpp, capi/libuwebsockets.h
Hello! 
I am working on Rust bindings to uWebSockets, and as far as I understand, defer is the only way to use the library in multiple threads (which is necessary in my case). 
So, this pull request adds a function `uws_loop_defer` to the CAPI.
Thank you for considering that PR.
=> Add uws_loop_defer function to uWebsockets CAPI

src/HttpResponse.h
Hey! 
I need to report a real size of a body in the HEAD response. It doesn't work without this patch.  
Thanks.
=> Fix reported content length for HttpResponse::endWithoutBody

src/WebSocket.h
Simple fix as described, silences the only unused variable warning
=> Silence unused variable warning

src/WebSocket.h
WS frame payload was errorneously lost in the shortcut branch of `WebSocket::send(std::string_view message, OpCode opCode, bool compress, bool fin)`, which resulted in incorrect byte sequences being sent on the wire. This PR fixes the bug.
=> Don't lose ws frame payload when its header went to backpressure

capi/libuwebsockets.cpp
I have tried out this fix and it seems to make the pause/resume functionality work correctly.  Addresses #1686 Thank you for considering it!
=> Fix uws_res_resume() API to call resume() instead of pause()

src/App.h, src/HttpContext.h
This allows for sockets that were obtained from an external `accept(2)` to be adopted into uWebSockets. 
Such sockets may come from another library, another external event-loop, or from a forked-server pattern, like [inetd](https://en.wikipedia.org/wiki/Inetd), [systemd-socket-activate](https://www.freedesktop.org/software/systemd/man/latest/systemd-socket-activate.html) etc.
This PR is based on https://github.com/uNetworking/uSockets/pull/214 for uSockets. 
Note: I'm unsure how Github handles PRs with submodules, hope I've done it right.
A forked process serving a single websocket session can increase safety, as each user is isolated in a separate process. In addition it can do impersonation via [setuid(2)](https://www.man7.org/linux/man-pages/man2/setuid.2.html) to restrict access on …
=> Feature / Adopt externally accepted sockets into uWebSockets.

src/App.h, src/WebSocket.h, src/WebSocketContext.h
The lambda is simply a wrapper to destruct UserData, which can instead be done by the caller, removing the need for it. In this case we also destruct UserData even if closeHandler is null, which would not have been done before.
=> Replace unnecessary lambda for close event

src/App.h
This fails clang-tidy and is probably a reasonable thing to change
=> Move deletion of topicTree to after use of the pointer in removePre/PostHandler

src/BloomFilter.h
`BloomFilter.h` uses `int32_t`, so it needs to include the `cstdint` header.
=> Add missing include cstdint in BloomFilter.h

src/MoveOnlyFunction.h
This fixes some warnings about the depreciation of std::aligned_storage when compiling using c++23
=> add feature test for __cpp_lib_move_only_function

src/TopicTree.h
Missing header file "exception". This causes a compiler error on at least MacOS when including the Websocket.h header file.
=> Update TopicTree.h to include missing header file for std::terminate

misc/READMORE.md
ping , pong handler should give std::string_view message argument. 
Otherwise, it throws error when compiling.
=> Update Example Code

src/WebSocketProtocol.h
For C++ reading from an inactive member of an union is technically undefined behavior. This also gets rid of the warning that MSVC was throwing about dst being potentially uninitialized variable being used.
Both versions compile down to the same assembly code, https://godbolt.org/z/cWbEnWYqM, with C++20 this could be changed to use bit_cast, and with C++23 it can be removed entirely to use std::byteswap
=> Less undefined behavior way of doing byte swap

src/WebSocketProtocol.h
=> add enable simd utf8 macro
